### ISSUE TITLE
更新了最新版本2.0.5还是崩溃

### ISSUE THREAD

**Issue by hapluto** [shubowen/VerticalRollingTextView#6]
java.lang.NegativeArraySizeException: -5
                                                                              at com.xiaosu.view.text.strategy.MultiLineStrategy.setupAutoSizeText(MultiLineStrategy.java:97)
                                                                              at com.xiaosu.view.text.strategy.MultiLineStrategy.getLayout(MultiLineStrategy.java:47)
                                                                              at com.xiaosu.view.text.VerticalRollingTextView.findLayoutByIndex(VerticalRollingTextView.java:196)
                                                                              at com.xiaosu.view.text.VerticalRollingTextView.onDraw(VerticalRollingTextView.java:144)

**Comment by shubowen** [comment]
清理studio缓存再试试

**Comment by hapluto** [comment]
清了还是一样的问题

**Comment by hapluto** [comment]
可以了，
